# Generated by Django 5.0.6 on 2024-06-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_rename_fk_institue_bankaccount_fk_institute"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="account_type",
            field=models.CharField(
                choices=[("GIRO", "Giro"), ("TAGESGELD", "Tagesgeld")],
                default="GIRO",
                max_length=15,
                verbose_name="Account Type",
            ),
        ),
    ]
