# Generated by Django 5.0.6 on 2024-06-20 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_bankaccount_account_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batchposition",
            name="fk_batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="batch_positions",
                to="portfolio.batch",
                verbose_name="Batch",
            ),
        ),
    ]
