# Generated by Django 5.0.6 on 2024-06-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_alter_batchposition_fk_batch"),
    ]

    operations = [
        migrations.AddField(
            model_name="security",
            name="ticker_symbol",
            field=models.CharField(
                default="tbd", max_length=5, verbose_name="Ticker Symbol"
            ),
            preserve_default=False,
        ),
    ]
