# Generated by Django 5.0.6 on 2024-06-28 07:33

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_batchposition_sell_fee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="fk_security",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="security",
                to="portfolio.security",
                verbose_name="Security",
            ),
        ),
        migrations.CreateModel(
            name="DividendPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.DecimalField(decimal_places=2, max_digits=14)),
                ("value_each", models.DecimalField(decimal_places=2, max_digits=14)),
                ("taxes", models.DecimalField(decimal_places=2, max_digits=14)),
                ("payment_date", models.DateField(default=datetime.date.today)),
                (
                    "fk_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.asset",
                    ),
                ),
            ],
        ),
    ]
