# Generated by Django 5.0.6 on 2024-06-28 08:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0008_alter_asset_fk_security_dividendpayment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="amount_currency",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="fk_account",
        ),
        migrations.AddField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("EXECUTED", "Executed"),
                    ("FAILED", "Failed"),
                    ("ROLLED_BACK", "Rolled back"),
                ],
                default="DRAFT",
                max_length=11,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("DEPOSIT", "Deposit"),
                    ("WITHDRAWAL", "Withdrawal"),
                    ("TRANSFER", "Transfer"),
                    ("SELL", "Sell"),
                    ("BUY", "Buy"),
                ],
                default="DEPOSIT",
                max_length=15,
            ),
        ),
        migrations.CreateModel(
            name="AccountBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=14)),
                ("booking_date", models.DateField(default=datetime.date.today)),
                (
                    "fk_bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.bankaccount",
                    ),
                ),
                (
                    "fk_transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.transaction",
                    ),
                ),
            ],
        ),
    ]
