# Generated by Django 5.0.6 on 2024-06-28 12:21

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0009_remove_transaction_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountbooking",
            name="booking_date",
            field=models.DateField(
                default=datetime.date.today, verbose_name="Booking Date"
            ),
        ),
        migrations.AlterField(
            model_name="accountbooking",
            name="fk_bank_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="portfolio.bankaccount",
                verbose_name="Bank Account",
            ),
        ),
        migrations.AlterField(
            model_name="accountbooking",
            name="value",
            field=models.DecimalField(
                decimal_places=2, max_digits=14, verbose_name="Value"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="description",
            field=models.TextField(
                blank=True, max_length=500, verbose_name="Description"
            ),
        ),
    ]
