# Generated by Django 5.0.6 on 2024-07-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0011_accountbooking_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="depot",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
