# Generated by Django 5.0.6 on 2024-07-03 13:35

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0013_alter_depot_is_active_alter_institute_short_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="institute",
            name="logo",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                default=1,
                force_format="PNG",
                keep_meta=True,
                quality=-1,
                scale=None,
                size=[300, 300],
                upload_to="whatever",
            ),
            preserve_default=False,
        ),
    ]
