# Generated by Django 5.0.6 on 2024-07-08 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0015_person_picture_alter_institute_logo"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="asset",
            unique_together={("fk_security", "fk_depot")},
        ),
    ]
