# Generated by Django 5.0.6 on 2024-07-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0017_batchpositionbooking"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="description",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
