# Generated by Django 5.0.6 on 2024-07-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0018_batch_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchposition",
            name="comment",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
