# Generated by Django 5.0.6 on 2024-07-10 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0019_batchposition_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bankaccount",
            name="balance",
        ),
        migrations.RemoveField(
            model_name="bankaccount",
            name="balance_currency",
        ),
        migrations.DeleteModel(
            name="DividendPayment",
        ),
    ]
