# Generated by Django 5.0.6 on 2024-07-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0020_remove_bankaccount_balance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchposition",
            name="blocking_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
