# Generated by Django 5.0.6 on 2024-07-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0022_paymentprovider_dividend_paymentcard"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentprovider",
            name="short_name",
            field=models.CharField(default="", max_length=10),
        ),
    ]
