# Generated by Django 5.0.6 on 2024-07-16 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0023_paymentprovider_short_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentcard",
            name="karten_folge_nummer",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Kartenfolgenummer",
            ),
        ),
        migrations.AlterField(
            model_name="paymentcard",
            name="valid_month",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
                verbose_name="MM",
            ),
        ),
        migrations.AlterField(
            model_name="paymentcard",
            name="valid_year",
            field=models.IntegerField(
                default=2022,
                validators=[django.core.validators.MinValueValidator(2022)],
                verbose_name="YY",
            ),
        ),
        migrations.AlterField(
            model_name="paymentprovider",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="paymentprovider",
            name="short_name",
            field=models.CharField(
                default="", max_length=10, verbose_name="Short Name"
            ),
        ),
    ]
